---
title: "520A_project"
author: "Zhipeng Zhu"
date: "2/7/2021"
output:
  html_document:
    theme: spacelab
    toc: yes
    df_print: paged
  pdf_document: default
urlcolor: BrickRed
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(ggfortify)
library(lubridate)
library(bsts)
library(mice)
```

# Data Preparing
```{r}
data = read.csv("../data/sp500.csv")
vix = read.csv("../data/VIX_History.csv")
data$Date = as.Date(data$Date)
vix$DATE = as.Date(vix$DATE, format = "%m/%d/%Y")
```

```{r}
vix = vix %>% 
  group_by(Date=floor_date(DATE, "month")) %>%
  summarize(VIX=mean(CLOSE)) %>%
  filter(Date < "2018-05-01")
head(vix, 10)
```

```{r}
data = data %>% filter(Date > "1989-12-01")
head(data, 10)
```

```{r}
data = inner_join(data, vix) %>% 
  rename(CPI = Consumer.Price.Index,
         LIR = Long.Interest.Rate) 
```

```{r}
data = data %>% dplyr::select(Date, SP500, CPI, LIR, PE10, VIX, Dividend, Earnings)
```

```{r}
md.pattern(data)
```

```{r}
tempData = mice(data,m=5,maxit=50,meth='pmm',seed=500)
data = complete(tempData,1)
```

```{r}
summary(is.na(data))
```

# EDA
## Plots
```{r}
p_sp500 = data %>% 
  ggplot(aes(x = Date, y = SP500)) +
  geom_point(size = 1)
p_cpi = data %>% 
  ggplot(aes(x = Date, y = CPI)) +
  geom_line(color = "red")
p_lir = data %>% 
  ggplot(aes(x = Date, y = LIR)) +
  geom_line(color = "red")
p_pe10 = data %>% 
  ggplot(aes(x = Date, y = PE10)) +
  geom_line(color = "blue")
p_div = data %>% 
  ggplot(aes(x = Date, y = Dividend)) +
  geom_line(color = "blue")
p_earn = data %>% 
  ggplot(aes(x = Date, y = Earnings)) +
  geom_line(color = "blue")
p_vix = data %>% 
  ggplot(aes(x = Date, y = VIX)) +
  geom_line(color = "red")
```

```{r}
p_sp500
```

```{r}
p_vix
```

```{r}
p_lir
```

```{r}
p_cpi
```

```{r}
p_pe10
```

```{r}
p_div
```

```{r}
p_earn
```

# BSTS
```{r}
data_ts = xts(data[-1], data$Date)
```

```{r, include=FALSE}
ss = AddLocalLinearTrend(list(), data_ts$SP500)
ss = AddSeasonal(ss, data_ts$SP500, nseasons = 12)
model = bsts(SP500 ~ ., state.specification = ss, data =
                data_ts, niter = 1000)
```

```{r}
summary(model)
```

