---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r Package, message = FALSE}
library(dplyr)
library(ggplot2)
library(lubridate)
library(reshape2)
library(gridExtra)
```


Variable to kept:   
* SP500  
* Dividend   
* Earnings  
* Consumer Price Index  
* Long Interest Rate  
* PE10



```{r Load the data, message=FALSE}
data <- read_csv("data/sp500.csv")
# View the data
str(data)
data$Date = as.Date(data$Date)
# Exclude records without PE10
data = data %>% filter(!is.na(PE10))

# Select designated varibales as shown in the proposal
data <- data %>% #select(SP500,`Dividend,Earnings`, `Consumer Price Index`, PE10) %>% 
  dplyr:: rename(CPI = 'Consumer Price Index', LIR = 'Long Interest Rate') %>%
  select(SP500, Date,Dividend,Earnings, CPI,LIR)

# Filter data starting from 1972
data <- data %>% filter(Date >= '1972-01-01')
```


```{r  Visualize SP500 over Time}
data %>% ggplot(aes(x=Date, y= SP500)) +
  geom_line()
```

```{r correlation heatmap}
cormat <- round(cor(data %>% select(-Date),use = "complete.obs"),2)
melted_cormat <- melt(cormat)
#head(melted_cormat)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))
```

```{r Bivariate Analysis: repsonese with each predictor}
p1 <- ggplot(data, aes(x=Dividend, y= SP500)) + 
  geom_point(size = 0.5)+
  geom_smooth()

p2 <- ggplot(data, aes(x=Earnings, y=SP500)) + 
  geom_point(size = 0.5)+
  geom_smooth()

p3 <- ggplot(data, aes(x=CPI, y=SP500)) + 
  geom_point(size = 0.5)+
  geom_smooth()

p4 <- ggplot(data, aes(x=LIR, y=SP500)) + 
  geom_point(size = 0.5)+
  geom_smooth()

cowplot::plot_grid(p1,p2,p3,p4, ncol = 2)
```

```{r}

```

















